FROM  node:20.11.0-alpine3.19

# Create a directory  and go to directory 
WORKDIR /app

# Copy the package.json file to my current directory for install necessary dependence  
COPY package.json .

# Install the dependence
RUN npm install

# Copy other file to my current directory
COPY . .

# Build for hot reloading
CMD [ "npm", "run", "dev"]

