version: '3.8'

services:
  express-typescript-docker:
    environment:
      - NODE_ENV=development
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: express-typescript-docker
    volumes:
      - ./server/src:/app/src
    expose:
      - "3003"
    ports:
      - "3003:3003"
      - "9229:9229"
    command: npm run dev

  nextjs-typescript-docker:
    environment:
      - NODE_ENV=development
    build:
      context: ./nextjs
      dockerfile: Dockerfile.dev
    container_name: nextjs-typescript-docker
    restart: always
    volumes:
      - ./nextjs:/app
      - /app/node_modules
    expose:
      - "3002"
    ports:
      - "3002:3002"
    
  react-typescript-docker:
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:5173
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: react-typescript-docker
    volumes:
      - ./client/src:/app/src
    expose:
      - "5173"
    ports:
      - "5173:5173"
    depends_on:
      - express-typescript-docker

 