version: '3.8'

services:
  express_container:
    environment:
      - NODE_ENV=development
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: express_container
    volumes:
      - ./server/src:/app/src
    expose:
      - "3003"
    ports:
      - "3003:3003"
      - "9229:9229"
    command: npm run dev

  nextjs_container:
    environment:
      - NODE_ENV=development
    build:
      context: ./nextjs
      dockerfile: Dockerfile.dev
    container_name: nextjs_container
    restart: always
    volumes:
      - ./nextjs:/app
      - /app/node_modules
    expose:
      - "3002"
    ports:
      - "3002:3002"
    depends_on:
      - cache
      - express_container
    
  client_container:
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:5173
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client_container
    volumes:
      - ./client/src:/app/src
    expose:
      - "5173"
    ports:
      - "5173:5173"
    depends_on:
      -  nextjs_container

  cache:
    image: redis:latest
    command: redis-server
    restart: always
    volumes:
      - cache:/data
    ports:
      - 6379:6379

volumes:
  cache:
    driver: local
 
